version: '3'

services:
  app:
    image: container-registry.oracle.com/database/free:latest
    container_name: 'oracle_database'
    environment:
      - 'ORACLE_PWD=root'
      - 'ORACLE_CHARACTERSET=AL32UTF8'
      # Test connection can be done using 'Database=FREEPDB1'
    ports:
      - '1522:1521'
    restart: 'on-failure'